version: '3.8'

services:
  app:
    build:
      context: ./DevOps_Project
      dockerfile: Dockerfile
    container_name: spring_app
    image: openjdk:11-jre-slim  # Use a JDK compatible with your Spring app
    ports:
      - "8082:8080"  # Host port 8082 mapped to container port 8080 for the Spring app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0  # MySQL version 8.0
    container_name: mysql_db
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
    environment:
      MYSQL_DATABASE: devops  # Database name
      MYSQL_ROOT_PASSWORD: root  # Root password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
