version: '3.8'

services:
  app:
    build:
      context: ./DevOps_Project
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8082:8080"  # Change the host port to 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: