version: '3.8'

services:
  app:
    build:
      context: ./DevOps_Project
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8082:8080"  # Host port 8082 mapped to container port 8080 for the Spring app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
      - nexus
      - sonarqube

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"  # Nexus default port
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
    volumes:
      - nexus_data:/nexus-data

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"  # SonarQube default port
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    depends_on:
      - db-sonarqube

  db-sonarqube:
    image: postgres:12
    container_name: db-sonarqube
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana default port
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  nexus_data:
  sonarqube_db_data:
  grafana_data:
