FROM openjdk:17-jdk-slim
# Expose the application's port (default Spring Boot port
EXPOSE 8082
# Copy the Spring Boot application JAR file to the container
ADD target/DevOps_Project-1.0.jar DevOps_Project-1.0.jar
# Run the application
ENTRYPOINT ["java", "-jar", "/DevOps_Project-1.0.jar"]